### PR TITLE
Article about workflows

### PR DESCRIPTION
**Pull request by stefanloerwald**
This is also to test PR functionality.

~~@MarkStega & @simonziegler: please do not merge. This PR also serves as a testing ground for workflows.~~

### CODE REVIEW

**Comment by stefanloerwald** [comment]
Maybe I have to comment on this?

(edit: turns out that wasn't necessary, but the workflow didn't trigger because of a missing PR type)

**Comment by stefanloerwald** [comment]
Hello! Your PR was automatically checked for differences in the demo page.

**Comment by stefanloerwald** [comment]
Hello! This comment was created automatically by the PR workflow, not by a human.

Your PR was automatically checked for differences in the demo page.
We do this to maintain high quality of the library. Below you'll find a summary of the differences we found.
Number of pages compared is 51
Estimates on size of difference per page
7 report/.md 157 total
The report is available as artifact on https://github.com/Material-Blazor/Material.Blazor/actions/runs/664381763

**Comment by stefanloerwald** [comment]
"Hello! This comment was created automatically by the PR workflow, not by a human.


Your PR was automatically checked for differences in the demo page.

We do this to maintain high quality of the library.
Below you'll find a summary of the differences we found.

## Summary
Number of pages compared is:
51

### Estimates on size of difference per page

   7 report/.md
 157 total

## Details
The report is available as artifact on https://github.com/Material-Blazor/Material.Blazor/actions/runs/664509624

## Actions
Please inspect all files with reported differences.
It is normal for the homepage to show a few differences, because the version identifier is always different."

**Comment by stefanloerwald** [comment]
"Hello! This comment was created automatically by the PR workflow, not by a human.


Your PR was automatically checked for differences in the demo page.

We do this to maintain high quality of the library.
Below you'll find a summary of the differences we found.

## Summary
Number of pages compared is:
51

### Estimates on size of difference per page

- report/.md: 7

## Details
The report is available as artifact on https://github.com/Material-Blazor/Material.Blazor/actions/runs/664613020

## Actions
Please inspect all files with reported differences.
It is normal for the homepage to show a few differences, because the version identifier is always different."

**Comment by simonziegler** [comment]
> This is also to test PR functionality.
> 
> @MarkStega & @simonziegler: please do not merge. This PR also serves as a testing ground for workflows.

@stefanloerwald - do you want to make this a draft PR?

BTW, what you're doing here is amazing.

**Comment by stefanloerwald** [comment]
> @stefanloerwald - do you want to make this a draft PR?
> 
> BTW, what you're doing here is amazing.

The tests regarding the workflows are done, so now this PR can actually be worked on regardless of them. I'm not the most eloquent writer for technical documentation, so it'll probably be a while until I find the muse to continue this article. Input from @MarkStega is highly appreciated ;-)

**Review by MarkStega — APPROVED** [review]

**Pull request merged**
